jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 2.52.10
    - continue-on-error: true
      name: Extract Build Id
      run: 'echo JFROG_CLI_BUILD_NAME=${{ github.event.inputs.buildName }} >> $GITHUB_ENV

        echo JFROG_CLI_BUILD_NUMBER=${{ github.event.inputs.buildNumber }} >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Download Release Files
      run: "jf rt download \\\n  --spec .github/release-files-spec.json \\\n  --spec-vars\
        \ \"buildname=$JFROG_CLI_BUILD_NAME;buildnumber=$JFROG_CLI_BUILD_NUMBER\"\n"
    - continue-on-error: true
      id: nexus
      uses: spring-io/nexus-sync-action@main
      with:
        create: true
        generate-checksums: true
        password: ${{ secrets.OSSRH_S01_TOKEN_PASSWORD }}
        staging-profile-name: ${{ secrets.OSSRH_STAGING_PROFILE_NAME }}
        upload: true
        username: ${{ secrets.OSSRH_S01_TOKEN_USERNAME }}
    - continue-on-error: true
      name: Print Staging Repo Id
      run: echo ${{ steps.nexus.outputs.staged-repository-id }}
name: Central Sync Create
on:
  repository_dispatch:
    types: trigger-ga___central-sync-create.yml
