jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: spring-io/nexus-sync-action@main
      with:
        close: true
        password: ${{ secrets.OSSRH_S01_TOKEN_PASSWORD }}
        staging-profile-name: ${{ secrets.OSSRH_STAGING_PROFILE_NAME }}
        staging-repo-id: ${{ github.event.inputs.stagedRepositoryId }}
        username: ${{ secrets.OSSRH_S01_TOKEN_USERNAME }}
name: Central Sync Close
on:
  repository_dispatch:
    types: trigger-ga___central-sync-close.yml
