jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: adopt
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY
          }}
        GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD
          }}
        GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER
          }}
      name: Build with Gradle
      run: ./gradlew clean build
    - continue-on-error: true
      if: ${{ failure() }}
      name: Tar Build Logs
      run: "mkdir -p build\ntar \\\n  -zc \\\n  --ignore-failed-read \\\n  --file\
        \ build/buildlogs.tar.gz \\\n  */build/reports \\\n  */*/build/reports\n"
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload Build Logs
      uses: actions/upload-artifact@v2
      with:
        name: buildlogs
        path: build/buildlogs.tar.gz
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
        os:
        - ubuntu-latest
  publish:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      env:
        JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 2.52.10
    - continue-on-error: true
      name: Configure JFrog Cli
      run: "jf gradlec \\\n  --use-wrapper \\\n  --uses-plugin \\\n  --deploy-ivy-desc=false\
        \ \\\n  --server-id-resolve=repo.spring.io \\\n  --server-id-deploy=repo.spring.io\
        \ \\\n  --repo-resolve=snapshot \\\n  --repo-deploy=snapshot\necho JFROG_CLI_BUILD_NAME=spring-statemachine-main\
        \ >> $GITHUB_ENV\necho JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV\n"
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY
          }}
        GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD
          }}
        GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER
          }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
      name: Build and Publish Snapshot
      run: 'jf gradle clean build -x test artifactoryPublish

        '
    - continue-on-error: true
      name: Publish Build Info
      run: 'jf rt build-publish

        '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
