jobs:
  labeler:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Mangle Labels
      uses: crazy-max/ghaction-github-labeler@v3
      with:
        dry-run: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        skip-delete: false
        yaml-file: .github/labels-manage.yml
name: Labels Manage
on:
  repository_dispatch:
    types: trigger-ga___label-manage.yml
