jobs:
  labeler:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Rename Labels
      uses: crazy-max/ghaction-github-labeler@v3
      with:
        dry-run: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        skip-delete: true
        yaml-file: .github/labels-rename.yml
name: Labels Rename
on:
  repository_dispatch:
    types: trigger-ga___label-rename.yml
