jobs:
  build:
    runs-on: self-hosted
    services:
      mongodb:
        image: bitnami/mongodb
        ports:
        - 27017:27017
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: adopt
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew clean build -PstatemachineIncludeTags=mongodb
    - continue-on-error: true
      if: ${{ failure() }}
      name: Tar Build Logs
      run: 'mkdir -p build

        tar -zc --ignore-failed-read --file build/buildlogs.tar.gz */build/reports
        */*/build/reports

        '
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: buildlogs
        path: build/buildlogs.tar.gz
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
        os:
        - ubuntu-latest
name: MongoDB
on:
  repository_dispatch:
    types: trigger-ga___mongodb.yml
