jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew clean build
    - continue-on-error: true
      if: ${{ failure() }}
      name: Tar Build Logs
      run: "mkdir -p build\ntar \\\n  -zc \\\n  --ignore-failed-read \\\n  --file\
        \ build/buildlogs.tar.gz \\\n  */build/reports \\\n  */*/build/reports\n"
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload Build Logs
      uses: actions/upload-artifact@v2
      with:
        name: buildlogs
        path: build/buildlogs.tar.gz
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
        os:
        - ubuntu-latest
name: PR
on:
  repository_dispatch:
    types: trigger-ga___pr.yml
