jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Handle Stale Issues
      uses: jvalkeal/issue-handler@v0.0.6
      with:
        config: "{\n  \"recipes\": [\n    {\n      \"name\": \"Handle stale issues\"\
          ,\n      \"type\": \"staleIssues\",\n      \"issueSince\": \"2020-08-01\"\
          ,\n      \"issueBeforeStale\": 60,\n      \"issueBeforeClose\": 7,\n   \
          \   \"issueStaleMessage\": \"This issue is stale because it has been open\
          \ 60 days with no activity. Remove status/stale label or comment or this\
          \ will be closed in 7 days\",\n      \"issueCloseMessage\": \"Closing stale\
          \ issue due to inactivity\",\n      \"issueStaleLabel\": \"status/stale\"\
          ,\n      \"issueCloseLabel\": \"status/closed-as-stale\",\n      \"issueExemptLabels\"\
          : [\n        \"status/on-hold\",\n        \"type/bug\",\n        \"type/need-investigation\"\
          \n      ],\n      \"issueUnstaleWhenUpdated\": true\n    }\n  ]\n}\n"
        dry-run: true
        token: ${{ secrets.GITHUB_TOKEN }}
name: Stale Issues
on:
  repository_dispatch:
    types: trigger-ga___stale-issues.yml
